In [1]:
import numpy as np

Ejercicio 1

In [3]:
array1D = np.arange(0,5)
array1D 

array([0, 1, 2, 3, 4])

Ejercicio 2

In [16]:
import random

In [18]:
a = np.random.randint(0,9,25)

In [24]:
b = a.reshape(5,5)
b

array([[5, 4, 8, 7, 3],
       [3, 3, 4, 8, 7],
       [4, 5, 5, 2, 0],
       [0, 7, 5, 5, 6],
       [0, 4, 7, 3, 6]])

In [ ]:
a2 = np.reshape((5, 5))

Ejercicio 3

In [21]:
tiradas = np.random.randint(1,7, size = 100)
tiradas

array([2, 1, 6, 6, 6, 4, 4, 4, 6, 2, 4, 1, 1, 4, 3, 3, 2, 1, 5, 5, 6, 4,
       2, 2, 5, 1, 3, 3, 2, 5, 2, 3, 5, 4, 2, 2, 3, 6, 3, 2, 1, 6, 3, 1,
       4, 2, 6, 4, 3, 1, 6, 3, 1, 3, 6, 6, 3, 2, 6, 5, 1, 1, 6, 1, 5, 4,
       5, 6, 1, 1, 5, 6, 3, 2, 4, 3, 4, 1, 2, 4, 4, 5, 2, 1, 5, 4, 1, 4,
       6, 2, 6, 3, 5, 3, 5, 6, 5, 2, 1, 6])

Ejercicio 4

In [26]:
frecuencias = np.unique(tiradas,return_counts=True)
frecuencias

(array([1, 2, 3, 4, 5, 6]), array([18, 17, 16, 16, 14, 19], dtype=int64))