# Numpy

**NumPy** es una biblioteca de Python de código abierto que se utiliza para el cálculo científico y la computación numérica. 

NumPy proporciona estructuras de datos eficientes para representar y manipular matrices y arreglos multidimensionales, lo que la hace ideal para trabajar con datos numéricos y científicos.

Es una librería esencial para cualquier persona que trabaje con datos numéricos en Python, desde científicos de datos y analistas hasta ingenieros de software y estudiantes.

## Links de interes

- [Documentacion](https://numpy.org/doc/stable/user/index.html)
- [W3school](https://www.w3schools.com/python/numpy/default.asp)
- [Tutorial](https://www.geeksforgeeks.org/numpy-tutorial/)
- [NumPy Cheat Sheet](https://images.datacamp.com/image/upload/v1676302459/Marketing/Blog/Numpy_Cheat_Sheet.pdf)

## Instalacion

```
pip install numpy
```

## Importar libreria

In [2]:
import numpy as np

## Arreglos de NumPy

Los **arreglos NumPy** son la forma principal de almacenar datos utilizando la biblioteca NumPy. Son *similares a las listas normales en Python*, pero tienen la ventaja de ser más rápidas y tener más métodos integrados.

### Creacion de arreglos

Los arreglos de NumPy son creados llamando al **método array()** de la librería de NumPy. Dentro del método, se debe pasar una **lista**.

In [5]:
lista = [1, 2, 3, 4, 5]

arreglo = np.array(lista) # Se crea un arreglo de la lista de numeros

arreglo # No es necesario usar print()

array([1, 2, 3, 4, 5])

**array()** nos indica que esta ya no es una lista normal de Python, sino un **arreglo de NumPy**.

### Tipos de arreglos

#### Vectores

Los vectores son **arreglos de NumPy uni-dimensionales**.

In [7]:
vector = np.array(['A', 'B', 'C', 'D'])

vector

array(['A', 'B', 'C', 'D'], dtype='<U1')

#### Matrices

Las matrices son **arreglos bi-dimensionales** y son creadas pasando una **lista de listas** dentro del método **np.array()**.

In [11]:
lista_de_listas =  [[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]]

matriz = np.array(lista_de_listas)

matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

También se pueden usar los arreglos de NumPy para trabajar con matrices de tres, cuatro, cinco, seis o más dimensiones.

### Tipos de Datos

- np.int64: Numeros Enteros
- np.float32: Numeros Decimales
- np.complex : Numeros Complejos
- np.bool: Booleanos
- np.object: Objeto
- np.string_: Cadenas
- np.unicode_: Valor UNICODE

### Metodos de arreglos

Los arreglos de NumPy tienen una variedad de **métodos incorporados** que pueden resultarnos útiles. 

#### Obtener un rango de números con **arange()**

NumPy tiene un método útil llamado **arange()** que toma dos números y devuelve un *arreglo de números enteros que son mayores o iguales a (>=) el primer número y menores que (<) el segundo número*.

In [14]:
arreglo = np.arange(0,10)

arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

También se puede incluir un tercer argumento en el **método arange()** que proporciona un **tamaño de paso (incremento, decremento)** para que la función regrese. 

Pasar 2 como tercera variable devolverá cada segundo número en el rango, pasar 5 como tercera variable devolverá cada quinto número en el rango, y así sucesivamente.

In [15]:
arreglo = np.arange(1,11,2)

arreglo

array([1, 3, 5, 7, 9])

Funciona igual que con las listas de Python, inicio esta incluido pero fin no, y el ultimo valor representa el incremento o decremento.

In [21]:
lista = list(range(1,11,2))

lista

[1, 3, 5, 7, 9]

#### Generar Unos y Ceros con **zeros()**

Podemos **crear arreglos de ceros** utilizando el **método zeros()** de NumPy. 

Se le pasa la cantidad que se quiere generar como el argumento de la función. 

In [30]:
arreglo = np.zeros(5)

arreglo

array([0., 0., 0., 0., 0.])

También podemos indicar el **tipo de dato**, por ejemplo *tipo entero (int)*.

In [29]:
arreglo = np.zeros(5,"int")

arreglo

array([0, 0, 0, 0, 0])

De igual manera, podemos **crear arreglos de unos** utilizando el **método ones()** de NumPy. 

Se le pasa la cantidad que se quiere generar como el argumento de la función. 

In [32]:
arreglo = np.ones(5, "int")

arreglo

array([1, 1, 1, 1, 1])

#### Crear arreglo con un valor en específico usando **full()**

Crea un arreglo con un valor en **específico**. 

Tiene 2 argumentos principales: 

- **shape**: Tupla con las dimensiones.
- **fill_value**: Valor especifico.

In [92]:
arreglo = np.full(10, 25)

arreglo

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [93]:
arreglo = np.full((3, 3), 25)

arreglo

array([[25, 25, 25],
       [25, 25, 25],
       [25, 25, 25]])

#### Dividir uniformemente un rango de números con **linspace()**

Hay muchas situaciones en las que tienes un rango de números y te gustaría dividir por igual ese rango de números en intervalos. 

El método **linspace()** de NumPy permite resolver este problema, este metodo recibe tres *argumentos*:

- Inicio del intervalo.
- Fin del intervalo.
- Número de subintervalos en los que deseas que se divida el intervalo.

In [19]:
arreglo_intervalo = np.linspace(0, 100, 5)
arreglo_intervalo

array([  0.,  25.,  50.,  75., 100.])

In [20]:
arreglo_intervalo = np.linspace(0, 100, 11)
arreglo_intervalo

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

#### Crear matrices identidad con **identity()**

El **arreglo identidad** es un **arreglo cuadrado cuyos valores diagonales son todos 1**. 

NumPy tiene un metodo incorporado que incluye un argumento para construir matrices de identidad llamado **identity()**.

![Arreglos Identidad](https://dcodingames.com/wp-content/uploads/2017/02/multmat2.fw_.png)

In [28]:
matriz_identidad = np.identity(1, "int") # Matriz identidad de 1x1

matriz_identidad

array([[1]])

In [29]:
matriz_identidad = np.identity(2, "int") # Matriz identidad de 2x2

matriz_identidad

array([[1, 0],
       [0, 1]])

In [26]:
matriz_identidad = np.identity(5, "int") # Matriz identidad de 5x5

matriz_identidad

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### Crear números aleatorios con **random()**

NumPy tiene varios métodos integrados que te permiten **crear matrices de números aleatorios**. 

Cada uno de estos métodos comienza con el metodo **random()**. 

In [37]:
#Devuelve una muestra de números aleatorios entre 0 y 1.

# Arreglo unidimensional
arreglo_aleatorio = np.random.rand(5)

# Arreglo bidimensional
matriz_aleatoria = np.random.rand(2, 2)

In [33]:
arreglo_aleatorio

array([0.37584268, 0.00294674, 0.28578705, 0.09428867, 0.29804807])

In [38]:
matriz_aleatoria

array([[0.05153609, 0.08687108],
       [0.46654131, 0.38331863]])

In [52]:
"""
NOTA: 
La distribución normal estándar es una distribución de probabilidad continua que se caracteriza por su forma acampanada, 
simétrica y con un pico en la media. 

La distribución normal es un modelo teórico capaz de aproximar satisfactoriamente el valor de una variable aleatoria a una situación ideal. 

La media de la distribución normal estándar es 0 y la desviación estándar es 1.
"""

#Devuelve una muestra de números aleatorios entre 0 y 1, siguiendo la distribución normal

arreglo_aleatorio = np.random.randn(5)

In [53]:
arreglo_aleatorio

# Los números son todos diferentes y se distribuyen de forma simétrica alrededor de la media, que es 0.

array([ 0.62228238, -2.25279122,  0.5678657 , -0.56904015, -0.89268693])

In [68]:
#Devuelve una muestra de números enteros que son mayores o iguales que 'low' y menores que 'high', segun un tamaño 'size'.

# np.random.randint(low, high, size)

arreglo_aleatorio = np.random.randint(1,10,5)

arreglo_aleatorio

array([5, 2, 1, 6, 3])

#### Remodelar matrices con **reshape()**

Es posible tomar una matriz con ciertas dimensiones y **transformar esa matriz en una forma diferente**. 

Por ejemplo, tenemos un arreglo unidimensional de 10 elementos y deseamos cambiarlo a un arreglo bidimensional de 2x5.

**ADVERTENCIA**

Para usar el método **reshape()**, la matriz original debe tener la misma cantidad de elementos que la matriz en la que se esta tratando de remodelar.

In [70]:
matriz_1 = np.array([0, 1, 2, 3, 4, 5])

matriz_2 = matriz_1.reshape(2, 3) # 2 * 3 = 6 elementos

matriz_2

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
matriz_1 = np.array([0, 1, 2, 3, 4, 5])

matriz_2 = matriz_1.reshape(3, 2) # 3 * 2 = 6 elementos

matriz_2

array([[0, 1],
       [2, 3],
       [4, 5]])

#### Conocer tamaño de un arreglo con **.shape**

Se puede determinar la forma actual de un arreglo NumPy con el **atributo .shape**

In [45]:
matriz_2.shape

(3, 2)

#### Conocer tamaño de un arreglo con **len()**

In [47]:
matriz_1 = np.array([0, 1, 2, 3, 4, 5])

len(matriz_1)

6

In [57]:
matriz_2 = np.array([[0, 1, 2],
                     [3, 4, 5]])

len(matriz_2) # Nro de filas

2

#### Conocer las dimensiones de un arreglo con **.ndim**

In [53]:
matriz_1.ndim

1

In [54]:
matriz_2.ndim

2

#### Conocer cantidad de elementos de un arreglo con **.size**

In [58]:
matriz_1.size

6

In [59]:
matriz_2.size

6

#### Conocer el tipo de dato de los elementos de un arreglo con **.dtype**

In [64]:
matriz_1.dtype # Entero de 32 bits

dtype('int32')

In [69]:
matriz_3 = np.array(["a", "b", "c"])

matriz_3.dtype.name # Nombre del tipo de dato # String de 32 bits

'str32'

#### Convertir los elementos de un arreglo a otro tipo de dato con **.astype()**

In [70]:
arreglo_1 = np.array([0, 1, 2, 3, 4, 5])

arreglo_casteado = matriz_1.astype("str")

arreglo_casteado 

array(['0', '1', '2', '3', '4', '5'], dtype='<U11')

In [72]:
arreglo_2 = np.array(["1", "2", "3"])

arreglo_casteado = arreglo_2.astype("int")

arreglo_casteado 

array([1, 2, 3])

#### Encontrar el valor máximo y mínimo de un arreglo con **max()** y **min()**

Podemos usar el método **max()** para encontrar el máximo valor de un arreglo de NumPy. 

In [85]:
# Definimos el arreglo
arreglo = np.arange(1,10)

arreglo

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
# Devuelve el máximo valor del arreglo
arreglo.max()

9

Podemos usar también el método **argmax()** para encontrar el índice del máximo valor dentro de un arreglo. 

Esto es útil cuando deseas encontrar la ubicación del valor máximo.

In [87]:
# Indica la posicion del maximo valor del arreglo
arreglo.argmax()

8

Igualmente, podemos usar los métodos **min()** y **argmin()** para encontrar el valor e índice del mínimo valor del arreglo.

In [88]:
# Devuelve el minimo valor del arreglo
arreglo.min()

1

In [89]:
# Indica la posicion del minimo valor del arreglo
arreglo.argmin()

0

#### Invertir un arreglo

In [73]:
# Definimos el arreglo
arreglo = np.arange(1,10)

arreglo

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arreglo_invertido = np.flip(arreglo)

arreglo_invertido

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [77]:
arreglo_invertido = arreglo[::-1]

arreglo_invertido

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [81]:
arreglo = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

np.flip(arreglo)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

#### Mover elementos de un arreglo

In [82]:
# Definimos el arreglo
arreglo = np.arange(1,10)

arreglo

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arreglo = np.roll(arreglo, 3)

arreglo

array([7, 8, 9, 1, 2, 3, 4, 5, 6])

#### Valores sin repetir de un arreglo

In [87]:
arreglo = np.array([[1,2,3],
                    [1,2,3],
                    [1,2,3]])

np.unique(arreglo)

array([1, 2, 3])

In [89]:
arreglo = np.array([[1,2,3],
                    [1,2,3],
                    [1,2,4]])

np.unique(arreglo, return_counts = True)

(array([1, 2, 3, 4]), array([3, 3, 2, 1], dtype=int64))

#### Ordenar un arreglo

In [93]:
arreglo = np.array([5,2,8,3,1,9])

arreglo.sort()

arreglo

array([1, 2, 3, 5, 8, 9])

#### Apariciones de cada elemento en un arreglo

In [96]:
arreglo = np.array([1,2,1,2,1,2])

np.bincount(arreglo)[1:]

array([3, 3], dtype=int64)

#### Filtrado de valores en un arreglo

In [97]:
arreglo = np.array([1,2,1,2,1,2])

np.where(arreglo > 1)  # Devuelve los indices de lso valores que cumplan la condicion

(array([1, 3, 5], dtype=int64),)

### Ejercicios de arreglos

1. Crea un arreglo 1D de tamaño 5 con valores enteros del 0 al 4.

2. Crea un arreglo 2D de tamaño 5x5 con valores aleatorios enteros entre 0 y 9.

3. Simular 100 tiradas de un dado.

4. Con lo obtenido en el ejercicio anterior, calcule la frecuencia de aparicion de cada valor del dado.

## Métodos y Operaciones de NumPy

In [94]:
# Generamos un arreglo para demostrar el uso de los metodos y las operaciones

arreglo = np.arange(0, 11)

arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Operaciones aritméticas

NumPy facilita realizar **operaciones aritméticas** con arreglos. 

Se pueden realizar usando un arreglo y un sólo número, o entre dos arreglos NumPy.

#### Suma

Al sumar un sólo número a un arreglo de NumPy, **ese número se sumara a cada elemento en el arreglo**.

In [99]:
arreglo_suma = arreglo + 2

arreglo_suma

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Tambien se pueden sumar dos arreglos NumPy usando el **operador +**. 

**Los arreglos se suman elemento por elemento** *(lo que significa que los primeros elementos se suman entre si, los segundos elementos se suman entre si, y así sucesivamente)*.

In [98]:
suma_de_arreglos = arreglo + arreglo

suma_de_arreglos

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### Resta

Como la suma, la resta se realiza elemento por elemento con arreglos de NumPy. 

In [100]:
arreglo_resta = arreglo - 4

arreglo_resta

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [101]:
resta_de_arreglos = arreglo - arreglo

resta_de_arreglos

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Multiplicación

La multiplicación también se realiza elemento por elemento tanto para casos de un sólo número como para casos de operaciones entre arreglos de NumPy.

In [102]:
arreglo_multi = arreglo * 2

arreglo_multi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
multi_de_arreglos = arreglo * arreglo

multi_de_arreglos

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### División

De nuevo, ocurre lo mismo con la division.

In [108]:
# Division
arreglo_div = arreglo / 2

arreglo_div

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [109]:
# Division entera
arreglo_div = arreglo // 2

arreglo_div

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5], dtype=int32)

In [110]:
div_de_arreglos = arreglo / arreglo

div_de_arreglos

C:\Users\pstef\AppData\Local\Temp\ipykernel_11320\3233020446.py:1: RuntimeWarning: invalid value encountered in divide
  div_de_arreglos = arreglo / arreglo


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Dado que no podemos dividir por cero, al hacerlo, el campo correspondiente se completa con un **valor nan**, que es la abreviatura de Python para *"No es un número" (“Not A Number”)*. 

Jupyter Notebook también imprimio una advertencia: *RuntimeWarning: invalid value encountered in...*

### Operaciones complejas

#### Raíz cuadrada

Se puede calcular la raíz cuadrada de cada elemento en un arreglo usando el método **np.sqrt()**.

In [111]:
arreglo_raiz_cuadrada = np.sqrt(arreglo)

arreglo_raiz_cuadrada

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

#### Exponencial

Se puede calcular la exponencial de cada elemento en un arreglo usando el método **np.exp()**.

In [118]:
arreglo_exp = np.exp(arreglo)

arreglo_exp

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

#### Seno trigonométrico

El metodo **np.sin()** calcula el seno trigonométrico de cada valor en el arreglo.

In [114]:
arreglo_seno = np.sin(arreglo)

arreglo_seno

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

#### Coseno trigonométrico

El metodo **np.cos()** calcula el coseno trigonométrico de cada valor en el arreglo.

In [117]:
arreglo_coseno = np.cos(arreglo)

arreglo_coseno

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

#### Logaritmo en base diez

Se puede calcular el logaritmo en base diez de cada valor en el arreglo con el metodo **np.log()**.

In [112]:
arreglo_log = np.log(arreglo)

arreglo_log

C:\Users\pstef\AppData\Local\Temp\ipykernel_11320\2065917500.py:1: RuntimeWarning: divide by zero encountered in log
  arreglo_log = np.log(arreglo)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

### Funciones agregadas

In [106]:
arreglo = np.array([1, 2, 3, 4])

arreglo

array([1, 2, 3, 4])

#### Suma

In [107]:
arreglo.sum()

10

#### Promedio

In [108]:
np.average(arreglo) # suma_elementos / cantidad_total

2.5

In [109]:
arreglo.mean()

2.5

#### Mediana

In [110]:
np.median(arreglo) # (menor + mayor) / 2

2.5

## Indexación y Asignación en NumPy

In [119]:
# Generamos un arreglo para demostrar la indexacion y asignacion

arreglo = np.random.rand(10)

arreglo

array([0.50103207, 0.93047569, 0.82091578, 0.58854946, 0.18984241,
       0.96445435, 0.46385326, 0.11479419, 0.50215802, 0.68922232])

In [121]:
# Redondeamos cada valor a maximo dos decimales
arreglo = np.round(arreglo, 2)

arreglo

array([0.5 , 0.93, 0.82, 0.59, 0.19, 0.96, 0.46, 0.11, 0.5 , 0.69])

### Acceder a un elemento específico del arreglo

Podemos acceder a un elemento específico de un arreglo NumPy de la misma forma que realiza con una lista normal de Python: 

Usando los **corchetes []**.

In [122]:
primero = arreglo[0]

primero

0.5

También **podemos acceder a múltiples elementos de un arreglo NumPy** usando los **dos puntos :**. 

- El **índice [2:]** selecciona cada elemento desde el índice 2 en adelante. 
- El **índice [:3]** selecciona cada elemento hasta el índice 3 excluido. 
- El **índice [2:4]** retorna cada elemento desde el índice 2 al índice 4, excluyendo este último.

In [123]:
# Retorna el arreglo completo
arreglo_completo = arreglo[:]

arreglo_completo

array([0.5 , 0.93, 0.82, 0.59, 0.19, 0.96, 0.46, 0.11, 0.5 , 0.69])

In [125]:
# Retorna el arreglo desde la posicion 1 hasta la ultima posicion
arreglo_completo = arreglo[1:]

arreglo_completo

array([0.93, 0.82, 0.59, 0.19, 0.96, 0.46, 0.11, 0.5 , 0.69])

In [126]:
# Retorna el arreglo desde la posicion 1 hasta la 3
arreglo_completo = arreglo[1:4] 

arreglo_completo

array([0.93, 0.82, 0.59])

### Asignación de valores en arreglos

Podemos asignar nuevos valores a un elemento de un arreglo NumPy usando el **operador =**, al igual que las listas de Python normales. 

In [127]:
arreglo = np.random.rand(10)

arreglo

array([0.24228655, 0.20849896, 0.34305915, 0.8214057 , 0.00543623,
       0.58908589, 0.29788852, 0.75592286, 0.96572252, 0.30398687])

In [128]:
arreglo = np.round(arreglo, 2)

arreglo

array([0.24, 0.21, 0.34, 0.82, 0.01, 0.59, 0.3 , 0.76, 0.97, 0.3 ])

In [129]:
# Cambia todos los elementos por 0
arreglo[:] = 0

arreglo

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [130]:
# Cambia los elementos por 1 desde la posicion 2 hasta la 4
arreglo[2:5] = 1

arreglo

array([0., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

### Referencia de arreglos

Veamos el siguiente codigo:

In [3]:
arreglo_1 = np.array([1, 2, 3, 4])

arreglo_1

array([1, 2, 3, 4])

In [4]:
arreglo_2 = arreglo_1[0:2]

arreglo_2

array([1, 2])

In [6]:
arreglo_2[0] = 10

arreglo_2

array([10,  2])

In [7]:
arreglo_1

array([10,  2,  3,  4])

La modificación de **arreglo_2** cambió también el valor de **arreglo_1**.

Por defecto, *NumPy no crea una copia de un arreglo cuando hace referencia a la variable del arreglo original usando el* **operador de asignación =**. En cambio, simplemente apunta la nueva variable a la anterior, lo que permite que la segunda variable realice modificaciones en la variable original.

Esto tiene una explicación lógica, el propósito de la referencia de arreglos es conservar poder computacional. Al trabajar con grandes conjuntos de datos, rápidamente te quedarías sin RAM si crearas un nuevo arreglo cada vez que quisieras trabajar con una porción de él.

Sin embargo, existe una solución para la referencia de arreglos. Se puede utilizar el método **copy()** para copiar explícitamente un arreglo NumPy.

In [9]:
arreglo_1 = np.array([1, 2, 3, 4, 5])

arreglo_1

array([1, 2, 3, 4, 5])

In [10]:
arreglo_2 = arreglo_1.copy()

arreglo_2

array([1, 2, 3, 4, 5])

In [11]:
arreglo_2[2] = 30

arreglo_2

array([ 1,  2, 30,  4,  5])

In [12]:
arreglo_1

array([1, 2, 3, 4, 5])

### Indexando arreglos NumPy de dos dimensiones

Primero definimos una matriz para ejemplificar:

In [13]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Hay dos formas de indexar un arreglo NumPy de dos dimensiones:

- **matriz[fila, columna]**
- **matriz[fila][colulma]**

In [14]:
# Primera fila:

matriz[0]

array([1, 2, 3])

In [15]:
# Primer elemento de la primera fila

matriz[0][0]

1

In [17]:
# Primer elemento de la primera fila

matriz[0,0]

1

In [33]:
# Desde la fila posicion 1 hasta la fila final.

matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [34]:
# Desde la primera columna hasta la columna en la posicion 0.

matriz[1:][:1]

array([[4, 5, 6]])

### Selección condicional de arreglos

Los arreglos NumPy permiten usar una función llamada **selección condicional**, que permite *generar un nuevo **arreglo de valores booleanos** que indican si cada elemento dentro del arreglo satisface una **declaración if** particular*.

In [36]:
arreglo = np.array([1, 2, 3, 4, 5])

arreglo

array([1, 2, 3, 4, 5])

In [39]:
seleccion_condicional = arreglo > 2

seleccion_condicional

array([False, False,  True,  True,  True])

También se puede generar un nuevo arreglo de valores que satisfagan esta condición, pasando la condición entre **corchetes []**.

In [42]:
seleccion_condicional = arreglo[arreglo > 2]

seleccion_condicional

array([3, 4, 5])

## Guardado en NumPy

In [111]:
arreglo = np.array([1, 2, 3, 4, 5])

In [123]:
np.savetxt("arreglos.txt", arreglo, fmt = "%.2f")

In [ ]:
np.savetxt("arreglos.txt", arreglo, fmt = "%.0f")

In [130]:
arreglotxt = np.loadtxt("arreglos.txt")

arreglotxt

array([1., 2., 3., 4., 5.])